// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk6jU8oS01y-Lgc6NoZOa6dCvBa4yXsV0',
    appId: '1:806206844737:android:c5d6e09f75e373f87bbbc0',
    messagingSenderId: '806206844737',
    projectId: 'rental-room-1224b',
    databaseURL: 'https://rental-room-1224b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rental-room-1224b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIJnzLTfFQ1NFfndYzhIUKybVt3etGL3A',
    appId: '1:806206844737:ios:bb42b5643a23eaa87bbbc0',
    messagingSenderId: '806206844737',
    projectId: 'rental-room-1224b',
    databaseURL: 'https://rental-room-1224b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rental-room-1224b.firebasestorage.app',
    iosClientId: '806206844737-r1i0aqvh7138vkmqs2ep143eus349hl3.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanArchitectureRentalRoom',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhzKbBkicM52-ebUEjF5dA9NIRDhYVMmo',
    appId: '1:806206844737:web:66bd300073d44c5f7bbbc0',
    messagingSenderId: '806206844737',
    projectId: 'rental-room-1224b',
    authDomain: 'rental-room-1224b.firebaseapp.com',
    databaseURL: 'https://rental-room-1224b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rental-room-1224b.firebasestorage.app',
    measurementId: 'G-76VQ67EBB5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIJnzLTfFQ1NFfndYzhIUKybVt3etGL3A',
    appId: '1:806206844737:ios:bb42b5643a23eaa87bbbc0',
    messagingSenderId: '806206844737',
    projectId: 'rental-room-1224b',
    databaseURL: 'https://rental-room-1224b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rental-room-1224b.firebasestorage.app',
    iosClientId: '806206844737-r1i0aqvh7138vkmqs2ep143eus349hl3.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanArchitectureRentalRoom',
  );

}